version: '3'

services:
  web:
    build:
      context: images/php
    container_name: php
    restart: unless-stopped
    volumes:
      - ./www:/var/www
      - ./moodledata:/var/moodledata
    networks:
      - moodle

  proxy:
    build:
      context: images/proxy
      dockerfile: Dockerfile
    container_name: proxy
    restart: unless-stopped
    ports:
      - ${WEB_PORT:-80}:80
    depends_on:
      - web
    volumes:
      - ./www:/var/www
      - ./images/proxy/nginx.conf:/etc/nginx/conf.d/nginx.conf
    networks:
      - moodle

  adminer:
    image: adminer
    restart: unless-stopped
    container_name: adminer
    ports:
      - "1212:8080"
    networks:
      - moodle

  db:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-db}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_USER: ${DB_LOGIN:-login}
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - moodle

  db_test:
    image: mysql
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: moodle
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - moodle

volumes:
  dbdata:
    driver: local

networks:
  moodle:
    driver: bridge