version: '3'

services:
  web:
    build:
      context: images/php
    container_name: php
    restart: unless-stopped
    volumes:
      - ./www:/var/www
      - ./moodledata:/var/moodledata
    networks:
      - moodle

  proxy:
    build:
      context: images/proxy
    container_name: proxy
    restart: unless-stopped
    ports:
      - ${WEB_PORT:-80}:80
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./www:/var/www
      - ./images/proxy:/etc/nginx/conf.d/
    networks:
      - moodle

  admine:
    image: adminer
    restart: unless-stopped
    container_name: adminer
    networks:
      - moodle

  db:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-db}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_USER: ${DB_LOGIN:-login}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - moodle

volumes:
  dbdata:
    driver: local

networks:
  moodle:
    driver: bridge